// <auto-generated />
using System;
using FutFut.Profile.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FutFut.Profile.Service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250612063211_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FutFut.Profile.Service.Entities.AboutPhotosEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfileEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileEntityId");

                    b.ToTable("AboutPhotos");
                });

            modelBuilder.Entity("FutFut.Profile.Service.Entities.PlayedHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PlayedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProfileEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileEntityId");

                    b.ToTable("PlayedHistory");
                });

            modelBuilder.Entity("FutFut.Profile.Service.Entities.ProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("FutFut.Profile.Service.Entities.SystemWorks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TimeOfWork")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SystemWorks");
                });

            modelBuilder.Entity("FutFut.Profile.Service.Entities.AboutPhotosEntity", b =>
                {
                    b.HasOne("FutFut.Profile.Service.Entities.ProfileEntity", null)
                        .WithMany("AboutPhotos")
                        .HasForeignKey("ProfileEntityId");
                });

            modelBuilder.Entity("FutFut.Profile.Service.Entities.PlayedHistoryEntity", b =>
                {
                    b.HasOne("FutFut.Profile.Service.Entities.ProfileEntity", null)
                        .WithMany("PlayedHistory")
                        .HasForeignKey("ProfileEntityId");
                });

            modelBuilder.Entity("FutFut.Profile.Service.Entities.ProfileEntity", b =>
                {
                    b.Navigation("AboutPhotos");

                    b.Navigation("PlayedHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
