services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmqFutFut
    restart: unless-stopped
    ports:
      - "5672:5672"     
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
        
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5666:5000"   
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ffmpeg-worker:
    build:
      context: ./ffmpeg-worker
    container_name: ffmpeg-worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - R2_ACCESS_KEY=your_key
      - R2_SECRET_KEY=your_secret
      - R2_BUCKET=your_bucket
      - R2_ENDPOINT=https://<account>.r2.cloudflarestorage.com
    volumes:
      - ./data:/app/data
    
volumes:
  pgdata:
  rabbitmqdata:
  esdata:
  redis_data: